version: '3'
services:
nestjs-app:
build:
dockerfile: Dockerfile
ports: - 3000:3000
env_file: -.env
depends_on:
- postgres

 postgres:
  image: postgres 
  environment:
   POSTGRES_USER: ${postgres}
   POSTGRES_PASSWORD: ${psql}
   POSTGRES_DB: ${cookmaster}
    ports: 
    - 5432:5432